[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHONUNBUFFERED = "1"
TZ = "UTC"
FLASK_ENV = "production"
GUNICORN_CMD_ARGS = "--log-level info --timeout 120" 